### ISSUE TITLE
Bug: Documentation referring to Full stack 

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws-samples/appsync-chat-app-cdk#3]
Link is broken:
https://blog.focusotter.com/the-fullstack-guide-to-creating-appsync-apis-with-the-aws-cdk#heading-interacting-with-a-nextjs-frontend

<img width="824" alt="Screenshot 2023-03-23 at 7 55 00 PM" src="https://user-images.githubusercontent.com/11032490/227412473-57cc26b2-e61a-4e32-b48f-376c3f8cccde.png">

**Comment by mtliendo** [comment]
Thanks @MichaelWalker-git for letting me know! I'll get that updated Monday, in the meantime, the correct link is [here](https://blog.focusotter.cloud/the-fullstack-guide-to-creating-appsync-apis-with-the-aws-cdk)

While I got your attention though, just a heads up that there is an updated AppSync post up that uses JavaScript resolvers instead of VTL. It's part of a full series that you can checkout [here](https://blog.focusotter.cloud/series/aws-for-frontend-devs). Would love to hear your thoughts on it!
